### ISSUE TITLE
Erro com Fill Letters

### ISSUE THREAD

**Issue by kleeedolinux** [Vitor1-1Santana/CMSPTasksDoer#4]
set. 25, 2024 9:07:50 PM com.vitorsantana.cmsptasksdoer.cmspobjects.Question <init>
SEVERE: java.lang.IllegalArgumentException: No enum constant com.vitorsantana.cmsptasksdoer.cmspobjects.Question.Types.fill_letters
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
set. 25, 2024 9:07:50 PM com.vitorsantana.cmsptasksdoer.cmspobjects.Question <init>
SEVERE: java.lang.IllegalArgumentException: No enum constant com.vitorsantana.cmsptasksdoer.cmspobjects.Question.Types.fill_letters
STATUS CODE: 200
set. 25, 2024 9:07:50 PM com.vitorsantana.cmsptasksdoer.cmspobjects.Question <init>
SEVERE: java.lang.IllegalArgumentException: No enum constant com.vitorsantana.cmsptasksdoer.cmspobjects.Question.Types.fill_letters
STATUS CODE: 200
set. 25, 2024 9:07:50 PM com.vitorsantana.cmsptasksdoer.cmspobjects.Question <init>
SEVERE: java.lang.IllegalArgumentException: No enum constant com.vitorsantana.cmsptasksdoer.cmspobjects.Question.Types.fill_letters
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
set. 25, 2024 9:07:51 PM com.vitorsantana.cmsptasksdoer.cmspobjects.Question <init>
SEVERE: java.lang.IllegalArgumentException: No enum constant com.vitorsantana.cmsptasksdoer.cmspobjects.Question.Types.fill_letters
STATUS CODE: 200
STATUS CODE: 200
set. 25, 2024 9:07:51 PM com.vitorsantana.cmsptasksdoer.cmspobjects.Question <init>
SEVERE: java.lang.IllegalArgumentException: No enum constant com.vitorsantana.cmsptasksdoer.cmspobjects.Question.Types.fill_letters
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
STATUS CODE: 200
Exception in thread "Thread-1" java.lang.NullPointerException: Cannot invoke "com.vitorsantana.cmsptasksdoer.cmspobjects.Question$Types.ordinal()" because "this.typeT" is null
        at com.vitorsantana.cmsptasksdoer.cmspobjects.Question.answerQuestion(Question.java:93)
        at com.vitorsantana.cmsptasksdoer.CMSPTasksDoer$1.lambda$run$0(CMSPTasksDoer.java:133)
        at java.base/java.util.ArrayList$Itr.forEachRemaining(Unknown Source)
        at com.vitorsantana.cmsptasksdoer.CMSPTasksDoer$1.run(CMSPTasksDoer.java:128)

aparentemente ele não consegue fazer todos os tipos de tarefas mais novas

**Comment by kleeedolinux** [comment]
![image](https://github.com/user-attachments/assets/d8b918d7-2bb4-45e2-95bc-cb8a00dbc247)
outra coisa ele  salva como rascunho

**Comment by kleeedolinux** [comment]
Essas tarefas não tinham nenhuma questão de texto

**Comment by Vitor1-1Santana** [comment]
O programa realmente não consegue fazer todos os tipos de questões, é difícil implementar um método de resolver uma questão específica no código, pois, eu preciso ter a tarefa primeiro. Mas mesmo assim, o programa não era suposto dar erro ao encontrar este tipo de problema, era suposto ele pular a questão e salvar a tarefa como rascunho. Obrigado por reportar isso.

Sobre ele salvar todas as atividades como rascunho, isso já foi um descuidado meu, eu acabei criando a Realese, mas esqueci de alterar a variavel responsável por definir se as tarefas são salvas como rascunho para "falso"(Eu defini como "verdadeiro" para testar a funcionalidade). Eu já havia notado este bug hoje, e estava prestes a corrigi-lo, mas obrigado por reportar mesmo assim.
