### ISSUE TITLE
Não acertar a respostas.

### ISSUE THREAD

**Issue by Vitor1-1Santana** [Vitor1-1Santana/CMSPTasksDoer#7]
### Discussed in https://github.com/Vitor1-1Santana/CMSPTasksDoer/discussions/6

<div type='discussions-op-text'>

<sup>Originally posted by **kleeedolinux** September 27, 2024</sup>
Bom, a maioria das pessoas que utilizarem isto é pra ganahr nota, porém os professores não conseguem ver quanto você acertou ou não (exceto o que for de escrever como redação). Então eu pensei, que tal você adicionar uma opção pra que ele não precse necessariamente acertar as respostas corrgindo assim alguns problemas.</div>

Criar uma opção nova, que permite o programa alterar de comportamento sobre o acerto de questões.

**Comment by kleeedolinux** [comment]
Como está o progresso?

**Comment by Vitor1-1Santana** [comment]
> Como está o progresso?

Não muito bem, minha conta foi suspensa recentemente devido a um login suspeito, conversei com o suporte, quatro dias depois eles me responderam, e minha conta voltou ao normal. Nestes 4 dias eu pausei completamente o desenvolvimento do projeto. Mas agora que está tudo de volta ao normal, vou retomar.
